baseurl: "/"
languageCode: "en-us"
languageLang: "en"
title: "OWASP ZAP"
enableEmoji: true
summaryLength: 48

taxonomies:
  tag: "tags"

params:
  description: The worldâ€™s most widely used web app scanner. Free and open source. Actively maintained by a dedicated international team of volunteers.
  EditContent:
    BaseUrl: https://github.com/zaproxy/zaproxy-website/blob/master/site/content/
    Label: Edit on GitHub

# Menu
menu:
  nav:
    - name:  "Home"
      URL:  "/"
      weight:  1

    - name:  "Blog"
      URL:  "/blog/"
      weight:  2

    - name:  "Videos"
      URL: /videos/
      weight:  3

    - name:  Documentation
      URL: /docs/
      weight:  4

    - name:  Get Involved
      URL: /get-involved/
      weight:  5

    - name:  "Support"
      URL:  /support/
      weight:  6


  footer: 
    - name:  "Home"
      URL:  "/"
      weight:  1

    - name:  "Blog"
      URL:  "/blog/"
      weight:  2

    - name:  "Videos"
      URL:  /videos/
      weight:  3

    - name:  "Get Involved"
      URL:  /get-involved/
      weight:  4

    - name:  "Support"
      URL:  /support/
      weight:  5

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds:  ["taxonomy", "taxonomyTerm"]
