baseurl: "/"
languageCode: "en-us"
languageLang: "en"
title: "OWASP ZAP"
enableEmoji: true
summaryLength: 48

taxonomies:
  tag: "tags"

params:
  description: The worldâ€™s most widely used web app scanner. Free and open source. Actively maintained by a dedicated international team of volunteers.
  EditContent:
    BaseUrl: https://github.com/zaproxy/zaproxy-website/blob/master/site/content/
    Label: Edit on GitHub

# Menu
menu:
  nav:
    - name:  "Home"
      URL:  "/"
      weight:  1

    - name:  "Blog"
      URL:  "/blog/"
      weight:  2

    - name:  "Videos"
      URL: /videos/
      weight:  3

    - name:  Documentation
      URL: /docs/
      weight:  4

    - name:  Community
      URL: /community/
      weight:  5

  footer: 
    - name:  "Home"
      URL:  "/"
      weight:  1

    - name:  "Blog"
      URL:  "/blog/"
      weight:  2

    - name:  "Videos"
      URL:  /videos/
      weight:  3

    - name:  Community
      URL: /community/
      weight:  4

    - name:  Statistics
      URL: /statistics/
      weight:  5
